- content/en/docs/guides/structuring-software-with-ocm.md
- content/en/docs/scope.md
Fixes links to spec in documentation pages.
> Fix Broken URLs in Documentation

- content/en/docs/cli-reference/get/get_credentials.md
- go.mod
- package.json
Changes:
- Update `go.mod` with the new repo uri
- Update `package.json` to use the open-component-model org instead of gardener org
- Remove Gardener from Config credential matcher [^1]
[^1]: https://github.com/open-component-model/ocm/issues/183
> Update repo URI from gardener to open-component-model

- config/_default/menus/menus.en.toml
- content/en/spec/_index.md
- static/schemas/component-descriptor-v2
- static/schemas/component-descriptor-v3alpha1
Schema should be accessible via the ocm.software domain. Links to schema are also present on the spec page.
Fixes #13
> Add json schema to website

- content/en/docs/installation.md
Short info added regarding the go/bin path, where the OCM CLI is going to be installed into.
Slightly unclear where the installed binary is located after installation.
> Adding Installation-Path-Info

- .github/workflows/update-cli-docs.yaml
This PR ensures that the latest_version tag is updated when a website updated is triggered.
> Ensure `./config` is updated when releasing docs

- content/en/docs/guides/getting-started-with-ocm-flux.md
- add the missing `cat` command from the components.yaml file creation
- correct the url for cloning `ocm-controller`
> fix: small correction in the getting started guide

- content/en/docs/installation.md
- static/install.sh
Adds an install script accessible at https://ocm.software/install.sh
This enables us to install the ocm cli in scenarios where homebrew might not be available.
> Add install.sh

- static/install.sh
We need to update the install script as the release artifacts have
changed the naming scheme.
Needs open-component-model/ocm#291 to merge first and a new release to be created.
> Update the install script

- static/install.sh
The HASH_URL used to validate checksums was incorrect.
> Fix installer script

- content/en/docs/guides/getting-started-with-ocm-flux.md
There is a broken link since ocm guides moved from ocm-spec repository to the website.
We can also remove the requirement for readers to checkout the ocm-controller repository in order to deploy.
> Update Flux getting started guide

- layouts/index.html
Ensure the button link on the homepage points to the new guides.
> Fix 'Get Started' button link

- content/en/docs/guides/getting-started-with-ocm.md
The variable OCM_REPO was not mentioned in getting started guide. This results in errors for people following the tutorial.
Fixes #
```feature user
```
> fix missing OCM_REPO var in getting started guide

- README.md
update URL to https://ocm.software
URL typo in README.MD #82
Fixes #
```feature user
```
> URL typo in README.MD #82

- content/en/docs/guides/input_and_access.md
Add documentation to access types for helm and npm artifacts.
Fixes #407
Please note that OCM CLI reference will be updated from the inline source documentation when the web-site is
generated from the latest source code.
```feature user
```
> add npm, helm access types

- config/_default/menus/menus.en.toml
- content/en/community/index.md
- content/en/project/about.md
- layouts/community/single.html
- layouts/partials/header/header.html
- layouts/partials/sidebar/auto-default-menu.html
This PR moves the community page to a dedicated community section separate from the project section.
The broken link to the non-existant `open-component-model/community` repository has also been fixed to point at `open-component-model/.github`.
> Community Page Update

- layouts/index.html
The 'Get Started' Link on the Landing Page points to a Guide about ocm and gitops. In my opinion, this should much rather link to the Getting Started with OCM Guide.
> Adjust Get Started Landing Page Link

- README.md
- content/docs/tutorials/build-deploy-software-via-helm-charts-with-ocm-101.md
This PR fixes a missing `apiVersion` in one of the YAML [descriptors](https://ocm.software/docs/tutorials/build-deploy-infrastructure-via-helm-charts-with-ocm/#apply-k8s-manifest) and updates the local execution guide.
-
> (fix) missing apiVersion in ocm-hello-world-podinfo ComponentVersion + (fix) local execution npm script

- content/docs/cli-reference/add/add_resources.md
- content/docs/tutorials/best-practices-with-ocm.md
This PR adds clarification on the sections for Building and Referencing a Multi-Arch Image. It also links to the Building a Multi-Arch Image section from the Add Resource topic.
- Closes https://github.com/open-component-model/ocm-project/issues/191
> Added clarification on multi-arch images

- .gitignore
- static/ocm
We decided to keep the restructured library in the current ocm repository. Therefore, for now, we'd like to be able to import the current library using the ocm url.
> Add dependency reference for ocm library

- content/docs/tutorials/build-deploy-software-via-helm-charts-with-ocm-101.md
I changed the name of the helm-chart-external reference to use the correct one, as it is defined in the input specification here:
https://github.com/open-component-model/ocm-website/blob/5ad2aa8dccbe4e035f11de6e837b02404376138e/content/docs/tutorials/build-deploy-software-via-helm-charts-with-ocm-101.md?plain=1#L99-L102
no issue created for it
> fixed reference for external helm chart

- static/install.sh
With v0.15 we're creating for each binary a dedicated checksum file.
> fix checksum URL and verification

- static/install.sh
use vercomp instead of pure bash sort
> use vercomp

- static/install.sh
This fixes a bug introduced in commit f1e6c16c613fa13b703bc4c78513d91e79e104dc.
The script uses `set -e`, so it will exit on any function call that returns a non-zero exit code.
Since *download_hash* is calling the vercomp version and vercomp returns 1,2 if the arguments (version1, version2) do not match, the script will exit.
> fix: do not exit script if vercomp returns non-zero value

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement_request.md
- .github/dependabot.yml
- .github/pull_request_template.md
- .github/settings.yml
same as https://github.com/open-component-model/ocm/pull/1150
> chore: inherit from .github labels

- .github/dependabot.yml
we should also configure `npm` updates
> chore: dependabot add package-ecosystem: "npm"

- .github/workflows/publish-site.yaml
- content/docs/examples/secure-software-delivery.md
> test different url

- assets/scss/common/_custom.scss
make margins smaller to allow more content to be displayed
> fix: adopt style and make content bigger

- hack/generate-cli-docs/generate_markdown.go
Add weight for the side-bar folder "cli-reference" to sort it behind "Component Descriptors"
> fix: add weight for generated cli reference

- package-lock.json
- package.json
revert patch version for thulite doks-core package
> chore: correct npm package

- static/open-component-model/bindings/go/descriptor/v2
create vanity for the v2 descriptor
> chore: add descriptor v2 vanity url

- static/open-component-model/bindings/go/credentials
makes it so `ocm.software/open-component-model/bindings/go/credentials` resolves correctly
> chore: make sure that credentials package is added to vanity urls so that go module resolution works for it

- config/_default/menus/menus.en.toml
- content/community/community.md
- layouts/community/_markup/render-heading.html
- layouts/community/single.html
re-introduce permalinks for the community page. These got lost, because we introduced a special rendering for the community side to make it centric, instead of attached to the left ,margin.
> fix: update community URLs and add layout to community pages

- assets/scss/common/_custom.scss
The grey logo text in header and on main page should be clear white, not light grey.
> style: update logo colors for dark and light themes. Keep logo text in white always

- .github/config/linkinator.json
reduce concurrency even further to avoid 429 errors from GitHub...
> chore: reduce concurrency setting in linkinator configuration

- .github/config/linkinator.json
- .github/config/linkspector.yml
- .github/config/markdownlint-cli2.yml
- .github/config/markdownlint.yml
- .github/workflows/verify-html.yml
- .github/workflows/verify-markdown.yml
Due to issues with rate limits when checking links on gihub.com, we disabled link checking for GitHub.com. In addition to that we added broken link check using linkspector.
> chore: update linkinator configuration and change markdown checks like in open-component-model repo

- .github/config/.markdownlint-cli2.yaml
MD059 switched off for website documents.
> chore: switch off md059 markdown check. sort markdownlint rules.

- .github/workflows/verify-markdown.yml
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
exclude ocm v1 ref docs from markdown linter
> chore: update markdown linting configuration to exclude specific reference directories

- .github/workflows/publish-site.yaml
With the new setup of a multi-version website, pushes to all branches (main and website/**) need to trigger a publish of the website.
> chore: update branch filter in publish-site workflow to include website/**

- static/open-component-model/bindings/go/descriptor/normalisation
We need this to be able to import packages from the normalisation module
> chore: add normalisation module

- static/open-component-model/bindings/go/descriptor/normalisation
We need this to be able to import packages from the normalisation module.
(cherry picked from commit 5ffcd746677433a4a904f6a12bf8b148850bf46a)
> chore: add normalisation module (#571)

- .github/config/wordlist.txt
- content/community/community.md
- static/open-component-model/bindings/go/rsa
Add a section for SIGs to the community page.
> chore(docs): add Special Interest Groups (SIGs) section to community guidelines
