- content/en/docs/context.md
Changed content of the context page to be a bit more readable / understandable.
> adjusting context page

- content/en/docs/context.md
Some minor fixes of typos / wording for the context page.
> Minor fixes for context.md

- content/en/docs/cli-reference/transfer/transfer_artefacts.md
Related to: https://github.com/open-component-model/ocm/issues/183
> fix: cli/transfer/artefacts examples

- layouts/index.html
Update the homepage CTA to point towards getting started with Flux guide.
> Update home page CTA

- content/en/docs/guides/getting-started-with-ocm-flux.md
One Codeblock was not correctly encapsulated in ```
Fixes #
```feature user
```
> Small fix for the getting started guide

- content/en/docs/guides/getting-started-with-ocm-flux.md
fix typos
Fixes #
```feature user
```
> Minor typos in Getting Started guides.

- content/en/docs/guides/getting-started-with-ocm-flux.md
Fixes open-component-model/ocm#232
> Fix error in flux guide

- content/en/docs/guides/getting-started-with-ocm-flux.md
Updates to getting started with flux guide.
> Update Getting Started with Flux & OCM

- hack/generate-cli-docs/main.go
This command does not require documentation on the website atm.
> remove bootstrap command from whitelist

- content/en/docs/guides/getting-started-with-ocm-flux.md
> Updated the getting started guide

- content/en/docs/guides/getting-started-with-ocm-flux.md
> Fix component version name to component

- content/en/docs/guides/getting-started-with-ocm-flux.md
> Update the guide to use createFluxSource

- .github/workflows/update-cli-docs.yaml
The update CLI workflow now updates the latest_version parameter in config/_default/params.toml
Co-authored by: Niki Manoledaki <niki@weave.works>
> Update CLI workflow to capture repository_dispatch events

- content/en/docs/guides/getting-started-with-ocm.md
- content/en/docs/guides/structuring-software-with-ocm.md
* enhance OCM guide with deploy and update sections
* fix duplicated title
Fixes #
```feature user
```
> add deployment, update sub-chapters to guide

- content/en/docs/guides/best-practices-with-ocm.md
- content/en/docs/guides/getting-started-with-ocm-flux.md
- content/en/docs/guides/getting-started-with-ocm.md
- content/en/docs/guides/input_and_access.md
- content/en/docs/guides/structuring-software-with-ocm.md
Add section to guides with input types and access types
Fixes #
```feature user
```
> Input and access types

- content/en/project/security.md
Adds a security page providing information about vulnerability reporting, disclosure and advistories.
Closes open-component-model/ocm#340
> Add Security Page

- hack/generate-cli-docs/generate_markdown.go
CLI reference contained some unwanted markup. Filter added.
Fixes #
[#89](https://github.com/open-component-model/ocm-website/issues/89)
```feature user
```
> add <pre> filter to CLI reference script

- .github/workflows/publish-site.yaml
- content/en/spec/_index.md
- generate-schema.yaml
Generate a human friendly schema page and link to it on the spec page.
Fixes #57
> update action to generate human friendly schema, add link on spec page

- content/en/docs/cli-reference/transfer/transfer_commontransportarchive.md
- content/en/docs/cli-reference/transfer/transfer_componentversions.md
typo described here: #107
Fixes #
```feature user
```
> spelling ist instead of it #107

- assets/scss/app.scss
- assets/scss/common/_global.scss
- assets/scss/components/_tables.scss
- config/_default/config.toml
- content/en/docs/cli-reference/_index.md
- content/en/docs/controller-reference/_index.md
- content/en/docs/controller-reference/api-reference/_index.md
- content/en/docs/controller-reference/api-reference/ocm-controller.md
- content/en/docs/controller-reference/installation.md
- content/en/docs/controller-reference/ocm-controller/_index.md
- content/en/docs/controller-reference/ocm-controller/component-version.md
- content/en/docs/controller-reference/ocm-controller/flux-deployer.md
- content/en/docs/controller-reference/ocm-controller/mutation.md
- content/en/docs/controller-reference/ocm-controller/resource.md
- content/en/docs/controller-reference/replication-controller/_index.md
- layouts/partials/sidebar/auto-collapsible-menu.html
- layouts/partials/sidebar/docs-menu.html
- package-lock.json
- package.json
This PR setups up the basic controller documentation structure and adds detail API reference and Component Version docs.
> Add controller docs to website

- layouts/index.html
Adds the badge icon to website homepage.
> Add Open SSF Badge

- content/en/spec/_index.md
This PR updates the URL for the spec version so that it points to release v0.1.0.
> Update Version URL

- layouts/index.html
> change docu

- content/en/docs/controller-reference/api-reference/replication-controller.md
- content/en/docs/controller-reference/installation.md
- content/en/docs/controller-reference/ocm-controller/component-version.md
- content/en/docs/controller-reference/replication-controller/_index.md
- content/en/docs/controller-reference/replication-controller/component-subscription.md
This PR adds detailed documentation for the replication controller.
This includes:
- API documentation for the ComponentSubscription CRD
- Full usage documentation
- Installation instructions
> Replication Controller Documentation

- content/en/docs/overview/context.md
another paragraph about gaining efficiency with re-use components modeled in OCM should be added.
Fixes #
```doc user
```
> add network effects

- content/en/docs/guides/input_and_access.md
minor corrections to format and typos.
Fixes #
```doc user
```
> minor corrections

- content/en/docs/guides/complex-component-structure-deployment.md
> fix: remove draft from post

- config/_default/params.toml
Ensure copyright date in footer and feed are up-to-date.
> Update copyright date in params.toml

- content/en/mpas/getting_started.md
- content/en/mpas/overview/installation.md
> minor changes

- content/en/mpas/getting_started.md
> change order and minor changes

- content/en/mpas/getting_started.md
This makes use of `mpas cli` to generate `projects`, `componentSubscription` and `productDeploymentGenerators` yamls.  We hope it makes for a better experience, by avoiding yamls manipulation.
> using mpas cli to generate CR yamls

- content/en/docs/controller-reference/installation.md
- content/en/docs/controller-reference/overview.md
This PR adds an overview page to the controllers documentation that describes the purpose and high-level architecture.
Part of #141 
> Add controllers overview page

- layouts/index.html
- layouts/partials/footer/script-footer.html
- layouts/partials/head/head.html
This PR adds the airgap demo video to the ocm homepage.
Part of #141 
> Add Airgap demo to homepage

- content/en/docs/component-descriptors/version-2.md
> correct schema from internal to v2

- content/en/mpas/core_concepts.md
- content/en/mpas/getting_started.md
- content/en/mpas/overview/_index.md
- content/en/mpas/overview/bootstrap.md
- content/en/mpas/overview/installation.md
updating the getting started guide to take into account last changes.
> updating the getting started guide

- content/en/docs/demos/_index.md
- content/en/docs/demos/secure-software-delivery.md
This PR adds the secure delivery demo to the website.
Closes #141 
> Add Secure Delivery Demo

- layouts/index.html
> add secure software supply chain context

- content/en/mpas/getting_started.md
> small typo

- content/en/mpas/getting_started.md
> some additional findings

- content/en/docs/cli-reference/configfile/_index.md
- content/en/docs/cli-reference/configfile/configfile_examples.md
- content/en/docs/cli-reference/configfile/configfile_syntax.md
Add Config file description and examples
> add config file and examples

- content/en/docs/cli-reference/configfile/configfile_syntax.md
> remove example from syntax md

- config/_default/params.toml
Update OCM version and year in footer
> update version and year

- content/en/docs/component-descriptors/version-2.md
- content/en/docs/component-descriptors/version-3.md
This PR add more explanation around versions
> explain versions

- content/en/docs/guides/getting-started-with-ocm.md
- content/en/project/about.md
> Correct link

- content/en/docs/component-descriptors/version-2.md
- content/en/docs/component-descriptors/version-3.md
- content/en/docs/controller-reference/api-reference/ocm-controller.md
> Upload new api doc

- content/en/spec/_index.md
> change layout for spec section

- content/en/docs/cli-reference/add/add_componentversions.md
- content/en/docs/guides/best-practices-with-ocm.md
- content/en/docs/guides/complex-component-structure-deployment.md
- content/en/docs/guides/getting-started-with-ocm.md
- content/en/docs/guides/structuring-software-with-ocm.md
- content/en/spec/_index.md
change components.yaml to component-constructor.yaml
> Change spec layout on website

- content/en/docs/controller-reference/api-reference/ocm-controller.md
> fix: using incorrect link to reference in external package

- static/testpackage
> test package

- content/en/spec/_index.md
> minor change in style

- static/ocm-cli
- static/ocm-core
- static/testpackage
> Testpackage

- content/en/docs/guides/structuring-software-with-ocm.md
- content/en/docs/overview/context.md
- content/en/docs/overview/scope.md
- content/en/project/about.md
> adopt scope and correct broken links

- .github/workflows/publish-site.yaml
> fix: generated schema location

- .github/workflows/publish-site.yaml
- package.json
> fix: location of the specification

- content/docs/controller/overview.md
> doc: update the controller overview documentation

- .github/workflows/publish-site.yaml
> correct action

- content/docs/tutorials/input_and_access.md
> npmPackage

- .github/workflows/publish-site.yaml
- layouts/index.html
> Minor change

- config/_default/params.toml
> version update after release 

- content/docs/tutorials/build-deploy-software-via-helm-charts-with-ocm-101.md
While reading through the guide I noticed a few links not working. Mainly for `localization` and `configuration`.
Completed the example output for exporting the kind config
> fix(tutorials): broken links, incomplete command

- content/docs/cli-reference/_index.md
> fix: cli reference title and weight

- assets/scss/common/_custom.scss
- hugo_stats.json
- layouts/_default/README
- layouts/_default/baseof.html
- layouts/_default/list.html
> fix: render index pages like they are single page

- content/docs/component-descriptors/_index.md
- content/docs/component-descriptors/version-2.md
- content/docs/component-descriptors/version-3.md
> fix: put back the component descriptor samples

- content/docs/overview/project.md
add small section about transport.
> add info about transport after image has been added

- content/docs/component-descriptors/version-2.md
- content/docs/component-descriptors/version-3.md
- content/docs/overview/project.md
> Correct version comments

- content/docs/tutorials/best-practices-with-ocm.md
remove chapter and correct multiple sections
> remove chapter and correct multiple sections

- content/docs/getting-started/getting-started-with-ocm/create-component-version.md
- content/docs/getting-started/getting-started-with-ocm/display-examine-component-versions.md
- content/docs/getting-started/getting-started-with-ocm/prerequisites.md
- content/docs/getting-started/getting-started-with-ocm/sign-component-versions.md
- content/docs/getting-started/getting-started-with-ocm/transport-component-versions.md
This PR removes the titles of the topics from the Getting Started section as they repeated and updated the header levels to one lower.
> Getting Started section - Removed titles and updated headers

- content/docs/getting-started/getting-started-with-ocm/create-component-version.md
This PR fixes broken links in the OCM website.
> Fixed broken links - 2024.06

- content/docs/getting-started/getting-started-with-ocm/prerequisites.md
> Fixed broken links

- content/docs/overview/some_terms.md
This PR cleans up the updated Terminology topic.
> Cleaned up Terminology topic

- content/docs/overview/specification.md
> remove schema versions

- content/docs/controller/controller-reference/ocm-controller/component-version.md
- content/docs/controller/overview.md
- content/docs/tutorials/build-deploy-software-via-helm-charts-with-ocm-101.md
- content/docs/tutorials/complex-component-structure-deployment.md
> feat: update the helm deployment tutorial for ocm

- static/install.sh
add version check to be able to install versions < 0.15.0
> add version check

- content/docs/tutorials/input_and_access.md
fixes https://github.com/open-component-model/ocm-website/issues/325
> add ocm commands to show all available options

- content/docs/tutorials/complex-component-structure-deployment.md
correct api version in example
> Correct-api-version-in-doc

- .github/workflows/update-security-txt.yaml
Weekly check for updated security.txt as GH action
> feature: add gh action to update security.txt

- .github/workflows/update-security-txt.yaml
add workflow_dispatch to be able to manually trigger action
> feature: add workflow_dispatch to be able to manually trigger action

- .github/workflows/publish-site.yaml
- content/docs/examples/secure-software-delivery.md
> Test different url

- README.md
in the past we had some issues with the publishing step...
> chore: let's show last publish site status

- content/docs/tutorials/build-deploy-software-via-helm-charts-with-ocm-101.md
> remove wrong attribute

- static/open-component-model
> feat: add open-component-model repository to vanity url

- static/open-component-model
> fix: add runtime subpackage to the vanity url

- static/open-component-model
- static/open-component-model-bindings-go-runtime
> fix: module path for bindings/go/runtime

- static/open-component-model/bindings/go/runtime
> fix: code location for the actual code

- static/open-component-model/bindings/go/runtime
Reverts open-component-model/ocm-website#418
> Revert "fix: code location for the actual code"

- static/open-component-model/index.html
> fix: add index file for root module

- static/open-component-model/bindings/go/descriptor/runtime
> chore: maintain runtime package in package redirects

- static/open-component-model/bindings/go/ctf
> chore: vanity url maintenance for ctf

- static/open-component-model/bindings/go/dag
- static/open-component-model/bindings/go/oci
> chore: add vanity urls for ocm packages oci and dag

- content/docs/tutorials/best-practices-with-ocm.md
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
fix broken link
> chore: fix link

- content/docs/tutorials/best-practices-with-ocm.md
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
fix markdown lint errors
> chore: fix MD lint errors

- content/docs/community/community.md
- content/docs/community/ocm-community.ics
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
Updated meeting series to 4 weeks and with Teams link. ics file also updated.
> chore: update OCM community call schedule and details

- .github/workflows/verify-html.yml
> add permissions

- .github/workflows/update-security-txt.yaml
- .github/workflows/verify-markdown.yml
> add GHA permissions

- .github/config/htmltest.yml
- .github/workflows/verify-html.yml
Use new HTML (link) checker. It checks internal and external links.
fixes open-component-model/ocm-project/issues/498
> chore: update HTML verification workflow and add configuration file

- static/open-component-model/bindings/go/constructor
> chore: add constructor vanity url proxy

- content/docs/getting-started/installation.md
Related to https://github.com/open-component-model/ocm-project/issues/499
> chore: remove winget

- config/_default/languages.toml
this updates the website footer of our website to reflect the latest guidance of the NeoNephos foundation
fix https://github.com/apeirora/community/issues/46#issuecomment-3018359986
> chore: update website footer to latest

- .github/workflows/verify-markdown.yml
> chore: fix path to markdownlint configuration file in workflow

- .github/config/wordlist.txt
- .github/docs/how-to-create-new-docs.md
- .github/docs/templates/_index.md
- .github/docs/templates/new-doc.md
Add process description on how to add new documents to the website.
> chore: add new documentation templates and doc for content creation

- .github/scripts/build-multi-version.sh
- netlify.toml
Copy over fixes from website/current branch.
> fix: update build command in netlify.toml for deploy previews

- .github/workflows/update-cli-docs.yaml
> chore: update action name

- .github/workflows/legacy-update-cli-docs.yaml
> chore: fix go run with wrong path

- .github/workflows/update-cli-docs.yaml
> fix: run action against website/current on repo dispatch event

- .github/workflows/update-cli-docs.yaml
> fix: fix syntax error

- .github/workflows/legacy-update-cli-docs.yaml
> fix: rename to match filename

- config/_default/params.toml
> chore: update latest version to v0.30.0

- .github/workflows/milestone.yaml
correct behavior that action does not work for PRs from forks.
> chore(docs): change pull_request to pull_request_target in milestone workflow
